### ISSUE TITLE
Uncaught TypeError: $(...).countdown is not a function

### ISSUE THREAD

**Issue by AAlvarez90** [hilios/jQuery.countdown#217]
Not working on jQuery 3.1.0

**Comment by hilios** [comment]
Yes it does, check the continuous integration server:

(Teste scenarios)[https://github.com/hilios/jQuery.countdown/blob/master/test/scenarios.json]
(CI server)[https://travis-ci.org/hilios/jQuery.countdown#L438]
